version: '3.8'

services:
  cybersillbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cybersillbot
    command: ["python", "bot.py"]
    ports:
      - "8002:8000"
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=8089913787:AAFbEVkIDkKCENHsYQ1KPJzbAVYzUTLaxD4
      - CRYPTO_PAY_API_TOKEN=382721:AASJGhh5oXLJvuMsfhR5PTGUE3CrMGLKmVW
      - API_ID=10016773
      - API_HASH=788b3df4ef36b07ee6c8f75099b08bb2
      - PHONE=+84708137908