version: '3.8'

services:
  cybersillbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cybersillbot
    command: ["python", "bot.py"]
    ports:
      - "8002:8000"
    restart: unless-stopped
    environment:
      - HTTP_PROXY=http://kslxewcb:2aeup7adbyjv@136.0.207.84:6661
      - HTTPS_PROXY=http://kslxewcb:2aeup7adbyjv@136.0.207.84:6661